name: Build and Push Docker Image of CRM

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_USERNAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build  \
             --build-arg DB_USERNAME="${{ secrets.DB_USERNAME }}" \
             --build-arg DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
             --build-arg DB_HOST="${{ secrets.DB_HOST }}" \
             --build-arg JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
             -t crm .

    - name: Tag Docker image
      run: |
        docker tag crm ${{ secrets.ACR_USERNAME }}.azurecr.io/crm:latest

    - name: Push Docker image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_USERNAME }}.azurecr.io/crm:latest
    
